### ISSUE TITLE
Mac Adressen Candle 

### ISSUE THREAD

**Issue by Megawaldi** [Heckie75/mipow-bulbs#1]
Hallo Hackie75,
wir haben schon mal mit deinem alten Script geschrieben.
Jetzt habe ich versucht, meine Candles mit deinem neuen Script anzusteuern.
Leider finde ich kein einziges Gerät im scan, wogegen das alte Script alle findet.
Ich denke, das liegt daran, dass meine Geräte alle mit AC:6E beginnen und nicht enden, wie du im Python code erwartest ... 
Vielleicht kannst du dir das ja mal ansehen:

LE Scan ...
4C:92:63:56:83:11 (unknown)
4C:92:63:56:83:11 (unknown)
AC:E6:4B:06:77:E0 (unknown)
AC:E6:4B:06:77:E0 Teelicht2
AC:E6:4B:06:75:5B (unknown)
AC:E6:4B:06:75:5B Teelicht1
64:1C:AE:42:FA:01 (unknown)
3A:63:44:52:72:F2 (unknown)
AC:E6:4B:06:6F:52 (unknown)
AC:E6:4B:06:6F:52 Teelicht3
.....

Die Teelichter sind meine Candles ...

Viele Grüße
Megawaldi

**Comment by Heckie75** [comment]
@Megawaldi I have committed a change.

**Comment by Megawaldi** [comment]
Its working fine
